table_html = '<table class="entity_table"><tr><td>1 Corinthians</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:blue">312</td><td style="text-align:right"><i class="fa fa-male" style="font-size:58px ;color:blue"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i class="fa fa-map-marker" style="color:red; font-size:20px"></i></td><td style="color:red">29</td><td style="text-align:right">~11:1</td><td></td></tr>\n \
<tr><td>Pseudo-Athanasius</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:blue">150</td><td style="text-align:right"><i class="fa fa-male" style="font-size:40px ;color:blue"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i class="fa fa-map-marker" style="color:red; font-size:20px"></i></td><td style="color:red">20</td><td style="text-align:right">~8:1</td><td></td></tr>\n \
<tr><td>English fiction</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:blue">2117</td><td style="text-align:right"><i class="fa fa-male" style="font-size:32px ;color:blue"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i class="fa fa-map-marker" style="color:red; font-size:20px"></i></td><td style="color:red">349</td><td style="text-align:right">~6:1</td><td><div class="speech-bubble">Ratio from a sample of English fiction</div></td></tr>\n \
<tr><td>Pseudo-Ephrem</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:blue">103</td><td style="text-align:right"><i class="fa fa-male" style="font-size:31px ;color:blue"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i class="fa fa-map-marker" style="color:red; font-size:20px"></i></td><td style="color:red">18</td><td style="text-align:right">~6:1</td><td></td></tr>\n \
<tr><td>Apophthegmata</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:blue">225</td><td style="text-align:right"><i class="fa fa-male" style="font-size:30px ;color:blue"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i class="fa fa-map-marker" style="color:red; font-size:20px"></i></td><td style="color:red">40</td><td style="text-align:right">~6:1</td><td></td></tr>\n \
<tr><td>Shenoute</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:blue">385</td><td style="text-align:right"><i class="fa fa-male" style="font-size:30px ;color:blue"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i class="fa fa-map-marker" style="color:red; font-size:20px"></i></td><td style="color:red">69</td><td style="text-align:right">~6:1</td><td></td></tr>\n \
<tr><td>Dormition of John</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:blue">133</td><td style="text-align:right"><i class="fa fa-male" style="font-size:24px ;color:blue"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i class="fa fa-map-marker" style="color:red; font-size:20px"></i></td><td style="color:red">30</td><td style="text-align:right">~4:1</td><td></td></tr>\n \
<tr><td>Besa</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:blue">160</td><td style="text-align:right"><i class="fa fa-male" style="font-size:21px ;color:blue"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i class="fa fa-map-marker" style="color:red; font-size:20px"></i></td><td style="color:red">40</td><td style="text-align:right">~4:1</td><td></td></tr>\n \
<tr><td>Victor the General</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:blue">138</td><td style="text-align:right"><i class="fa fa-male" style="font-size:21px ;color:blue"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i class="fa fa-map-marker" style="color:red; font-size:20px"></i></td><td style="color:red">36</td><td style="text-align:right">~4:1</td><td></td></tr>\n \
<tr><td>Coptic average</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:blue">2647</td><td style="text-align:right"><i class="fa fa-male" style="font-size:20px ;color:blue"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i class="fa fa-map-marker" style="color:red; font-size:20px"></i></td><td style="color:red">709</td><td style="text-align:right">~4:1</td><td><div class="speech-bubble">This ratio is the Coptic average</div></td></tr>\n \
<tr><td>Ruth</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:blue">279</td><td style="text-align:right"><i class="fa fa-male" style="font-size:20px ;color:blue"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i class="fa fa-map-marker" style="color:red; font-size:24px"></i></td><td style="color:red">90</td><td style="text-align:right">~3:1</td><td></td></tr>\n \
<tr><td>Mark</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:blue">589</td><td style="text-align:right"><i class="fa fa-male" style="font-size:20px ;color:blue"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i class="fa fa-map-marker" style="color:red; font-size:29px"></i></td><td style="color:red">230</td><td style="text-align:right">~3:1</td><td></td></tr>\n \
<tr><td>Life of Cyrus</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:blue">102</td><td style="text-align:right"><i class="fa fa-male" style="font-size:20px ;color:blue"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i class="fa fa-map-marker" style="color:red; font-size:38px"></i></td><td style="color:red">52</td><td style="text-align:right">~2:1</td><td></td></tr>\n \
<tr><td>Life of Onnophrius</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:blue">71</td><td style="text-align:right"><i class="fa fa-male" style="font-size:20px ;color:blue"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i class="fa fa-map-marker" style="color:red; font-size:58px"></i></td><td style="color:red">55</td><td style="text-align:right">~1:1</td><td></td></tr>\n \</table> \
';

$("#table_people_places").empty();
$("#table_people_places").html(table_html);