table_html = '<table class="entity_table"><tr><td>Besa</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:#25d4d4">279</td><td style="text-align:right"><i title="abstract" class="fa fa-cloud" style="font-size:50px ;color:#25d4d4"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i title="object" class="fa fa-cube" style="color:green; font-size:20px"></i></td><td style="color:green">37</td><td style="text-align:right">~8:1</td><td></td></tr>\n \
<tr><td>1 Corinthians</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:#25d4d4">211</td><td style="text-align:right"><i title="abstract" class="fa fa-cloud" style="font-size:37px ;color:#25d4d4"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i title="object" class="fa fa-cube" style="color:green; font-size:20px"></i></td><td style="color:green">38</td><td style="text-align:right">~6:1</td><td></td></tr>\n \
<tr><td>Pseudo-Athanasius</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:#25d4d4">163</td><td style="text-align:right"><i title="abstract" class="fa fa-cloud" style="font-size:36px ;color:#25d4d4"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i title="object" class="fa fa-cube" style="color:green; font-size:20px"></i></td><td style="color:green">30</td><td style="text-align:right">~5:1</td><td></td></tr>\n \
<tr><td>Apophthegmata</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:#25d4d4">225</td><td style="text-align:right"><i title="abstract" class="fa fa-cloud" style="font-size:36px ;color:#25d4d4"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i title="object" class="fa fa-cube" style="color:green; font-size:20px"></i></td><td style="color:green">42</td><td style="text-align:right">~5:1</td><td></td></tr>\n \
<tr><td>Shenoute</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:#25d4d4">289</td><td style="text-align:right"><i title="abstract" class="fa fa-cloud" style="font-size:27px ;color:#25d4d4"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i title="object" class="fa fa-cube" style="color:green; font-size:20px"></i></td><td style="color:green">72</td><td style="text-align:right">~4:1</td><td></td></tr>\n \
<tr><td>Dormition of John</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:#25d4d4">127</td><td style="text-align:right"><i title="abstract" class="fa fa-cloud" style="font-size:25px ;color:#25d4d4"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i title="object" class="fa fa-cube" style="color:green; font-size:20px"></i></td><td style="color:green">34</td><td style="text-align:right">~4:1</td><td></td></tr>\n \
<tr><td>Pseudo-Ephrem</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:#25d4d4">97</td><td style="text-align:right"><i title="abstract" class="fa fa-cloud" style="font-size:22px ;color:#25d4d4"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i title="object" class="fa fa-cube" style="color:green; font-size:20px"></i></td><td style="color:green">29</td><td style="text-align:right">~3:1</td><td></td></tr>\n \
<tr><td>Ruth</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:#25d4d4">70</td><td style="text-align:right"><i title="abstract" class="fa fa-cloud" style="font-size:21px ;color:#25d4d4"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i title="object" class="fa fa-cube" style="color:green; font-size:20px"></i></td><td style="color:green">22</td><td style="text-align:right">~3:1</td><td></td></tr>\n \
<tr><td>Coptic average</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:#25d4d4">1864</td><td style="text-align:right"><i title="abstract" class="fa fa-cloud" style="font-size:20px ;color:#25d4d4"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i title="object" class="fa fa-cube" style="color:green; font-size:20px"></i></td><td style="color:green">619</td><td style="text-align:right">~3:1</td><td><div class="speech-bubble">This ratio is the Coptic average</div></td></tr>\n \
<tr><td>Life of Onnophrius</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:#25d4d4">83</td><td style="text-align:right"><i title="abstract" class="fa fa-cloud" style="font-size:20px ;color:#25d4d4"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i title="object" class="fa fa-cube" style="color:green; font-size:36px"></i></td><td style="color:green">50</td><td style="text-align:right">~2:1</td><td></td></tr>\n \
<tr><td>Life of Cyrus</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:#25d4d4">42</td><td style="text-align:right"><i title="abstract" class="fa fa-cloud" style="font-size:20px ;color:#25d4d4"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i title="object" class="fa fa-cube" style="color:green; font-size:46px"></i></td><td style="color:green">32</td><td style="text-align:right">~1:1</td><td></td></tr>\n \
<tr><td>Mark</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:#25d4d4">237</td><td style="text-align:right"><i title="abstract" class="fa fa-cloud" style="font-size:20px ;color:#25d4d4"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i title="object" class="fa fa-cube" style="color:green; font-size:48px"></i></td><td style="color:green">188</td><td style="text-align:right">~1:1</td><td></td></tr>\n \
<tr><td>Victor the General</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:#25d4d4">41</td><td style="text-align:right"><i title="abstract" class="fa fa-cloud" style="font-size:20px ;color:#25d4d4"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i title="object" class="fa fa-cube" style="color:green; font-size:66px"></i></td><td style="color:green">45</td><td style="text-align:right">~1:1</td><td></td></tr>\n \
<tr><td>English fiction</td><td style="text-align: right; vertical-align: middle; display:table-cell;"><span style="color:#25d4d4">652</td><td style="text-align:right"><i title="abstract" class="fa fa-cloud" style="font-size:20px ;color:#25d4d4"></i></td> <td style="vertical-align: middle; display:table-cell;"><span style="color:red"><i title="object" class="fa fa-cube" style="color:green; font-size:76px"></i></td><td style="color:green">826</td><td style="text-align:right">~1:1</td><td><div class="speech-bubble">Ratio from a sample of English fiction</div></td></tr>\n \</table> \
';

$("#table_abstract_object").empty();
$("#table_abstract_object").html(table_html);